---
name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [26, 27]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: '3.25.0'

      - name: Install dependencies
        run: rebar3 get-deps

      - name: Run xref analysis
        run: rebar3 as test xref

      - name: Run dialyzer analysis
        run: rebar3 as test dialyzer

      - name: Run hank analysis
        run: rebar3 hank

      - name: Run linting
        run: rebar3 lint

      #- name: Run Common Test
      #  run: rebar3 as test ct
